#!/bin/bash

# Exit immediately on any error to come.
set -e

# Import log functions.
. functions

# The directory the script lives in. Should be /var/opt/_bruder.
# TODO: Make it dynamic, wherever services live in.
__DIR__="$(cd "$(dirname "$0")" && pwd)"

# Set the working dir at the beginning. When running cronjobs, the
# relative path is not the directory the script being fired lives in.
cd $__DIR__

# first param (e.g. update)
action=$1

# second param (e.g. all or dirname)
target=$2

# First parameter has to be …muss…!
valid_actions=(muss)
if ! in_array "$action" "${valid_actions[@]}"; then
  log_info "❗" "Bruder [muss|…]?"
  exit 1
fi

# No target set?
if [ ! -n "$target" ]; then
  log_info "❗" "Bruder muss [update|backup|…]?"
  exit 1
fi

# Target is valid?
valid_targets=(update backup)
if [ "$action" = "muss" ]; then
  if ! in_array "$target" "${valid_targets[@]}"; then
    log_info "🙃" "Bruder muss los."
    exit 1
  fi
fi

################################
echo -e "\n"
log_time
################################

# Run backups for a given set if projects in the parent folder.
if [ "$action" = "muss" ] && [ "$target" = "backup" ]; then
  [ -f "./backup" ] && ./backup

  exit 1
fi

# Loop through the update-list file and run a set of docker
# commands to update all services to the latest release of their
# respective versions.
if [ "$action" = "muss" ] && [ "$target" = "update" ]; then

  void_run git fetch

  # Updates available for this script?
  if [[ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]]; then
    log_info "▶️" "Erstmal mich updaten…"
    log_run git pull
  fi

  log_info "▶️" "Ich lass Updates für alle Projekte laufen…"

  while IFS= read -r dir_name; do
    dir="/var/opt/$dir_name"

    # Directory doesn't exist?
    [ -d "$dir" ] || continue

    log_info "▶️" "$dir_name"

    cd $dir

    # Check, if any compose container is running.
    if docker compose ps -q | grep -q .; then

      # Run docker compose updates if a compose.yml file exists.
      if [ -f "compose.yml" ] || [ -f "docker-compose.yml" ]; then
        log_run docker compose pull
        log_run docker compose up -d
      else
        log_info "ℹ️" "Keine compose.yml gefunden!"
        continue
      fi
    else
      log_info "ℹ️" "Grad nicht an, update läuft still…"
      log_run docker compose pull
    fi
  done < list.update

  log_success "Alles klar, Bruder!"

  exit 1
fi
