#!/bin/bash

# Exit immediately on any error to come.
set -e

# The directory the script lives in. Should be /var/opt/_bruder.
# TODO: Make it dynamic, wherever services live in.
__DIR__="$(cd "$(dirname "$0")" && pwd)"

# Set the working dir at the beginning. When running cronjobs, the
# relative path is not the directory the script being fired lives in.
cd $__DIR__

# Import log functions.
. logger.sh

# first param (e.g. update)
action=$1

# second param (e.g. all or dirname)
target=$2

# First parameter has to be …muss…!
if [ "$action" != "muss" ]; then
  log_info "🩲" "Bruder [muss|…]?"
  exit 1
fi

# Second parameter will just accept …updaten… for now.
if [ "$target" != "updaten" ]; then
  log_info "🩲" "Bruder muss [updaten|…]?  test"
  exit 1
fi


################################
echo -e "\n"
log_info "🕰️" "$TIME"
log_info "🫰" "Was geht Bruder!"
################################


# Loop through the update-list file and run a set of docker
# commands to update all services to the latest release of their
# respective versions.
if [ "$target" = "updaten" ]; then

  log_command git fetch

  # Updates available for this script?
  if [[ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]]; then
    log_info "🫴" "Erstmal mich updaten…"
    log_command git pull
  fi

  log_info "🫴" "Ich lass Updates für alle Projekte laufen…"

  while IFS= read -r dir_name; do
    dir="/var/opt/$dir_name"

    # Directory doesn't exist?
    [ -d "$dir" ] || continue

    log_info "↪️" "$dir_name"

    cd $dir

    # Check, if any compose container is running.
    if docker compose ps -q | grep -q .; then

      # Run docker compose updates if a compose.yml file exists.
      if [ -f "compose.yml" ] || [ -f "docker-compose.yml" ]; then
        log_command docker compose pull
        log_command docker compose up -d
      else
        log_info "🫲" "Keine compose.yml gefunden, Bruder!"
        continue
      fi
    else
      log_info "🤫" "Grad nicht an, update läuft still…"
      log_command docker compose pull
    fi
  done < update-list

  log_success "Alles fertig Bruder, bis zum nächsten mal!"
fi
